### ISSUE TITLE
Cursor flickering when enter and leave insert mode

### ISSUE THREAD

**Issue by vaxowt** [alohaia/fcitx.nvim#1]
fcitx.nvim causes cursor flickering when enter and leave insert mode

**Comment by alohaia** [comment]
@vaxowt can you provide more details? What do you mean by "flickering"?

**Comment by vaxowt** [comment]
nvim version:
![image](https://user-images.githubusercontent.com/116184338/226643669-21502daf-6e64-4f4c-96dd-78d3e75fa7e1.png)

package manager: lazy.nvim

With fcitx.nvim enabled:

https://user-images.githubusercontent.com/116184338/226643313-3ff9c2d3-c203-4377-927d-4c93c0d5dd7b.mp4


Disable fcitx.nvim only:

https://user-images.githubusercontent.com/116184338/226643298-ab87405e-672b-4c38-b389-485c9d8cd354.mp4

**Comment by alohaia** [comment]
~~Does this happen with only fcitx.nvim enabled? I can't reproduce this.~~

I reproduced it. I'll try to fix it later.

**Comment by vaxowt** [comment]
> ~Does this happen with only fcitx.nvim enabled? I can't reproduce this.~
> 
> I reproduced it. I'll try to fix it later.

It works! Thank you.
